site_name: Algorithms & Data Structures
site_url: https://lgopractice.github.io/
theme:
  name: material
  font:
    text: "CT"
    code: "ML"
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    admonition:
      tip: material/lightning-bolt
  features:
    - navigation.path # A breadcrumb navigation is rendered above the title of each page.
    - navigation.expand # Left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually
    - navigation.footer  # Include links to the previous and next page of the current page
    - navigation.instant # Material for MkDocs now behaves like a Single Page Application
    - navigation.instant.prefetch # Start to fetch a page once the user hovers over a link
    - navigation.instant.progress # Show indicator if the page hasn't finished loading after 400ms

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.mark
  - md_in_html

extra_javascript:
  - assets/mathjax.js
  - assets/spoilers.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/custom.css
  - assets/spoilers.css

nav:
  - Stack: 
    - Introduction: "stack/index.md"
    - Problems: "stack/problems.md"
    - Foundations: 
      - Valid Parentheses: "stack/02.md"
      - Implement Queue using Two Stacks: "stack/03.md"
      - Implement Stack using Queues: "stack/04.md"
      - Min/Max Stack: "stack/05.md"
      - Backspace String Compare: "stack/06.md"
      - Remove Outermost Parentheses: "stack/07.md"
    - Monotonic Stack:
      - Next Greater Element I: "stack/08.md"
      - Next Greater Element II — circular array: "stack/09.md"
      - Daily Temperatures: "stack/10.md"
